kind: pipeline

steps:
  - name: UnitTest
    image: maven:3-jdk-11
    commands:
      - mvn package
      - mvn test
  - name: Sonar
    image: maven:3-jdk-11
    commands:
      - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=mora456 -Dsonar.host.url=http://52.249.33.202:9000
  - name: Production
    image: maven:3-jdk-11
    commands:
      - mvn tomcat7:deploy