kind: pipeline

steps:
  - name: UnitTest
    image: maven:3-jdk-11
    commands:
      - mvn package
      - mvn test
  - name: sonar
    image: maven:3-jdk-11
    commands:
      - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=mora456